export const plans = [
  {
    id: 1,
    title: "Básico con anuncios",
    subtitle: "720p",
    price: "5.99",
    quality: "Buena",
    resolution: "720p (HD)",
    home_devices: "1",
    download_devices: "0",
  },
  {
    id: 2,
    title: "Básico",
    subtitle: "720p",
    price: "7.99",
    quality: "Buena",
    resolution: "720p (HD)",
    home_devices: "2",
    download_devices: "1",
  },
  {
    id: 3,
    title: "Estándar",
    subtitle: "1080p",
    price: "11.99",
    quality: "Excelente",
    resolution: "1080p (Full HD)",
    home_devices: "3",
    download_devices: "2",
  },
  {
    id: 4,
    title: "Premium",
    subtitle: "4K + HDR",
    price: "15.99",
    quality: "Óptima",
    resolution: "4K (Ultra HD) + HDR",
    home_devices: "4",
    download_devices: "6",
  },
];
